// <auto-generated />
using System;
using FileAnalysisService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileAnalysisService.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20251210174932_AddAssignmentAndStudent")]
    partial class AddAssignmentAndStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalysisReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CheckedFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId2")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPlagiarism")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MatchedFileId")
                        .HasColumnType("uuid");

                    b.Property<double>("MaxSimilarityPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("SimilarityPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
